### PR TITLE
Fix the parse error on PHP 7.4

### LINKED ISSUE #289: PHP7.4 & guzzle
Since upgrading to php7.4 im getting

```
ParseError : syntax error, unexpected end of file, expecting :: (T_PAAMAYIM_NEKUDOTAYIM)
 vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:197
```
I have noticed this on multiple projects. I'll try to look into this later today, but as of now it's not really usable on php 7.4.

I only get this error when VCR is turned on.

### PR DESCRIPTION
**Pull request by morozov**
Do not return the stat since we don't know the resulting the size that the file will have after having all transformations applied. When including files, PHP 7.4 and newer are sensitive to file size reported by stat.

Fixes #289 (based on the recommendation from https://bugs.php.net/bug.php?id=79072).

### CODE REVIEW

**Comment by morozov** [comment]
This is what the PHPUnit output looks like now on PHP 7.4:
```
PHPUnit 5.7.23 by Sebastian Bergmann and contributors.

E.EEEE.........................................................................  79 / 271 ( 29%)
............................................................................... 158 / 271 ( 58%)
EEEEEEE........................example response................................................ 237 / 271 ( 87%)
...........................E..EEEE                                              271 / 271 (100%)

Time: 268 ms, Memory: 10.00MB

There were 17 errors:

1) VCR\CassetteTest::testInvalidCassetteName
Array and string offset access syntax with curly braces is deprecated

/home/morozov/php-vcr/vendor/mikey179/vfsStream/src/main/php/org/bovigo/vfs/vfsStream.php:354
/home/morozov/php-vcr/tests/VCR/CassetteTest.php:20

2) VCR\CassetteTest::testDontOverwriteRecord
Trying to access array offset on value of type null

/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:61
/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:124
/home/morozov/php-vcr/src/VCR/Cassette.php:71
/home/morozov/php-vcr/src/VCR/Cassette.php:59
/home/morozov/php-vcr/src/VCR/Cassette.php:91
/home/morozov/php-vcr/tests/VCR/CassetteTest.php:40

3) VCR\CassetteTest::testPlaybackAlreadyRecordedRequest
Trying to access array offset on value of type null

/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:61
/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:124
/home/morozov/php-vcr/src/VCR/Cassette.php:71
/home/morozov/php-vcr/src/VCR/Cassette.php:59
/home/morozov/php-vcr/src/VCR/Cassette.php:91
/home/morozov/php-vcr/tests/VCR/CassetteTest.php:50

4) VCR\CassetteTest::testHasResponseNotFound
Trying to access array offset on value of type null

/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:61
/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:124
/home/morozov/php-vcr/src/VCR/Cassette.php:71
/home/morozov/php-vcr/src/VCR/Cassette.php:59
/home/morozov/php-vcr/tests/VCR/CassetteTest.php:59

5) VCR\CassetteTest::testHasResponseFound
Trying to access array offset on value of type null

/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:61
/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:124
/home/morozov/php-vcr/src/VCR/Cassette.php:71
/home/morozov/php-vcr/src/VCR/Cassette.php:59
/home/morozov/php-vcr/src/VCR/Cassette.php:91
/home/morozov/php-vcr/tests/VCR/CassetteTest.php:66

6) VCR\Storage\YamlTest::testIterateOneObject
Trying to access array offset on value of type null

/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:61
/home/morozov/php-vcr/tests/VCR/Storage/YamlTest.php:128
/home/morozov/php-vcr/tests/VCR/Storage/YamlTest.php:27

7) VCR\Storage\YamlTest::testIterateTwoObjects
Trying to access array offset on value of type null

/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:61
/home/morozov/php-vcr/tests/VCR/Storage/YamlTest.php:128
/home/morozov/php-vcr/tests/VCR/Storage/YamlTest.php:42

8) VCR\Storage\YamlTest::testIterateFirstNestedObject
Trying to access array offset on value of type null

/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:61
/home/morozov/php-vcr/tests/VCR/Storage/YamlTest.php:128
/home/morozov/php-vcr/tests/VCR/Storage/YamlTest.php:58

9) VCR\Storage\YamlTest::testIterateSecondNestedObject
Trying to access array offset on value of type null

/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:61
/home/morozov/php-vcr/tests/VCR/Storage/YamlTest.php:128
/home/morozov/php-vcr/tests/VCR/Storage/YamlTest.php:74

10) VCR\Storage\YamlTest::testIterateEmpty
Trying to access array offset on value of type null

/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:61
/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:124
/home/morozov/php-vcr/tests/VCR/Storage/YamlTest.php:128
/home/morozov/php-vcr/tests/VCR/Storage/YamlTest.php:83

11) VCR\Storage\YamlTest::testStoreRecording
Trying to access array offset on value of type null

/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:61
/home/morozov/php-vcr/tests/VCR/Storage/YamlTest.php:97

12) VCR\Storage\YamlTest::testStoreTwoRecording
Trying to access array offset on value of type null

/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:61
/home/morozov/php-vcr/tests/VCR/Storage/YamlTest.php:115

13) VCR\VCRTest::testShouldDispatchBeforeAfterHttpRequestAndBeforeRecordWhenCassetteHasNoResponse
Trying to access array offset on value of type null

/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:61
/home/morozov/php-vcr/src/VCR/Storage/Yaml.php:124
/home/morozov/php-vcr/src/VCR/Cassette.php:71
/home/morozov/php-vcr/src/VCR/Videorecorder.php:223
/home/morozov/php-vcr/src/VCR/Videorecorder.php:291
/home/morozov/php-vcr/src/VCR/LibraryHooks/CurlHook.php:204
/home/morozov/php-vcr/src/VCR/LibraryHooks/CurlHook.php:154
/home/morozov/php-vcr/tests/VCR/VCRTest.php:58
/home/morozov/php-vcr/tests/VCR/VCRTest.php:174

14) VCR\VideorecorderTest::testHandleRequestRecordsRequestWhenModeIsNewRecords
Function ReflectionType::__toString() is deprecated

/home/morozov/php-vcr/tests/VCR/VideorecorderTest.php:138
/home/morozov/php-vcr/tests/VCR/VideorecorderTest.php:45

15) VCR\VideorecorderTest::testHandleRequestThrowsExceptionWhenModeIsNone
Function ReflectionType::__toString() is deprecated

/home/morozov/php-vcr/tests/VCR/VideorecorderTest.php:71

16) VCR\VideorecorderTest::testHandleRequestRecordsRequestWhenModeIsOnceAndCassetteIsNew
Function ReflectionType::__toString() is deprecated

/home/morozov/php-vcr/tests/VCR/VideorecorderTest.php:138
/home/morozov/php-vcr/tests/VCR/VideorecorderTest.php:92

17) VCR\VideorecorderTest::testHandleRequestThrowsExceptionWhenModeIsOnceAndCassetteIsOld
Function ReflectionType::__toString() is deprecated

/home/morozov/php-vcr/tests/VCR/VideorecorderTest.php:119
```
Fixing those issues requires PHPUnit upgrade and fixing other issues which are out of scope.

**Comment by janvernieuwe** [comment]
Any updates on merging this?

**Comment by carusogabriel** [comment]
@janvernieuwe I'll look into this during the week after I figure out how to make the build green again for old versions.

**Comment by tristanbes** [comment]
We're stuck with this issue too on PHP7.4

Thanks for providing this patch @morozov ! Looking forward to a release <3

**Comment by morozov** [comment]
@carusogabriel since it's really a blocker for being able to use PHP 7.4, would it make sense to release a patch before fixing the rest of the issues? From what I can tell, a significant part of the tests fail because of the old PHPUnit and other dependencies and may not affect end users.

FWIW, the PHPBrew tests are fine on PHP 7.4 with just this patch applied.

**Comment by janvernieuwe** [comment]
> @janvernieuwe I'll look into this during the week after I figure out how to make the build green again for old versions.

I got it working here: https://travis-ci.org/php-vcr/php-vcr/builds/619582565?utm_source=github_status&utm_medium=notification / https://github.com/php-vcr/php-vcr/pull/290

Or do you mean something else?

**Comment by veewee** [comment]
This fix also works for phpro/soap-client:
https://github.com/phpro/soap-client/pull/293
https://travis-ci.org/github/phpro/soap-client/builds/675274399

File: src/VCR/Util/StreamProcessor.php [hunk 1]
```diff
@@ -262,13 +262,17 @@ public function stream_seek($offset, $whence = SEEK_SET)
     /**
      * Retrieve information about a file resource.
      *
+     * Do not return the stat since we don't know the resulting the size that the file will have
```
Comment (Tobion) [inline src/VCR/Util/StreamProcessor.php:265]: lang: the resulting the size

**Comment by genintho** [comment]
Fixing compatibility with PHP 7.4 is probably worth a release. I know I would have saved a few hours 😄
